/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-02-25 15:37:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberPostcode_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/WEB_CODES/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Petopia/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1607397061812L));
    _jspx_dependants.put("jar:file:/C:/WEB_CODES/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Petopia/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>우편번호 검색</title>\r\n");

request.setCharacterEncoding("UTF-8");
String inputYn = request.getParameter("inputYn");
String roadFullAddr = request.getParameter("roadFullAddr");
String roadAddrPart1 = request.getParameter("roadAddrPart1");
String roadAddrPart2 = request.getParameter("roadAddrPart2");
String engAddr = request.getParameter("engAddr");
String jibunAddr = request.getParameter("jibunAddr");
String zipNo = request.getParameter("zipNo");
String addrDetail = request.getParameter("addrDetail");
String admCd = request.getParameter("admCd");
String rnMgtSn = request.getParameter("rnMgtSn");
String bdMgtSn = request.getParameter("bdMgtSn");
String detBdNmList = request.getParameter("detBdNmList");
String bdNm = request.getParameter("bdNm");
String bdKdcd = request.getParameter("bdKdcd");
String siNm = request.getParameter("siNm");
String sggNm = request.getParameter("sggNm");
String emdNm = request.getParameter("emdNm");
String liNm = request.getParameter("liNm");
String rn = request.getParameter("rn");
String udrtYn = request.getParameter("udrtYn");
String buldMnnm = request.getParameter("buldMnnm");
String buldSlno = request.getParameter("buldSlno");
String mtYn = request.getParameter("mtYn");
String lnbrMnnm = request.getParameter("lnbrMnnm");
String lnbrSlno = request.getParameter("lnbrSlno");
String emdNo = request.getParameter("emdNo");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("document.domain = \"localhost\";\r\n");
      out.write("\r\n");
      out.write("function init() {\r\n");
      out.write("\tvar url = location.href;\r\n");
      out.write("\tvar confmKey = \"devU01TX0FVVEgyMDIxMDEwNjE3MTEwOTExMDYzMzU=\"; // 승인키\r\n");
      out.write("\tvar resultType = \"4\"; // 도로명주소 검색결과 화면 출력내용, 1:도로명, 2:도로명+지번+상세보기(관련지번,관할주민센터), 3:도로명+상세보기(상세건물명), 4:도로명+지번+상세보기(관련지번,관할주민센터,상세건물명)\r\n");
      out.write("\tvar inputYn= \"");
      out.print(inputYn);
      out.write("\";\r\n");
      out.write("\tif(inputYn != \"Y\") {\r\n");
      out.write("\t\tdocument.form.confmKey.value = confmKey;\r\n");
      out.write("\t\tdocument.form.returnUrl.value = url;\r\n");
      out.write("\t\tdocument.form.resultType.value = resultType;\r\n");
      out.write("\t\tdocument.form.action=\"https://www.juso.go.kr/addrlink/addrLinkUrl.do\";\r\n");
      out.write("\t\tdocument.form.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\topener.jusoCallBack(\r\n");
      out.write("\t\t\t\t\"");
      out.print(roadFullAddr);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(roadAddrPart1);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(addrDetail);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(roadAddrPart2);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(engAddr);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(jibunAddr);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(zipNo);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(admCd);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(rnMgtSn);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(bdMgtSn);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(detBdNmList);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(bdNm);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(bdKdcd);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(siNm);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(sggNm);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(emdNm);
      out.write("\", \r\n");
      out.write("\t\t\t\t\"");
      out.print(liNm);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(rn);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(udrtYn);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(buldMnnm);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(buldSlno);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(mtYn);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(lnbrMnnm);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(lnbrSlno);
      out.write("\",\r\n");
      out.write("\t\t\t\t\"");
      out.print(emdNo);
      out.write("\"\r\n");
      out.write("\t\t\t\t);\r\n");
      out.write("\t\tclose();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"init();\">\r\n");
      out.write("\t<form id=\"form\" name=\"form\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"confmKey\" name=\"confmKey\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"returnUrl\" name=\"returnUrl\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"resultType\" name=\"resultType\" value=\"\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
