/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2021-02-25 05:53:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.letter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1607397061812L));
    _jspx_dependants.put("jar:file:/C:/WEB_CODES/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Petopia/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<!-- Popper 최신 버전 링크  -->\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap을 이용하기 위한 최신 버전 링크 -->\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("  src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("input[type=text][readonly],[type=textarea][readonly] {\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text]{\r\n");
      out.write("\tborder:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=textarea]{\r\n");
      out.write("\tborder:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title{\r\n");
      out.write("\tmargin-top:21px;\r\n");
      out.write("    margin-bottom: 21px;\r\n");
      out.write("    line-height: 22px;\r\n");
      out.write("    letter-spacing: -1px;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    color: #1e2732;\r\n");
      out.write("    padding-bottom: 15px;\r\n");
      out.write("    border-bottom: 1px solid #a4a9b0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".guide{\r\n");
      out.write("\tmargin-bottom: 14px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    line-height: 20px;\r\n");
      out.write("    letter-spacing: -1px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #757c8a;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table{\r\n");
      out.write("\ttable-layout: fixed;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    border-top: 1px solid #ececec;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    line-height: 20px;\r\n");
      out.write("    color: #5e636d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("    padding: 12px 20px 12px 20px;\r\n");
      out.write("    border-bottom: 1px solid #ececec;\r\n");
      out.write("    color: #5e636d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th{\r\n");
      out.write("\twidth:92px;\r\n");
      out.write("\tpadding: 13px 0 13px 20px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    color: #222;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    background: #f8f9fa;\r\n");
      out.write("    border-bottom: 1px solid #ececec;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#insert {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    border: 1px solid #2383dc;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    background: #2e8de5;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    line-height: 16px;\r\n");
      out.write("    padding: 11px 0;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".deleteletter{\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 38px;\r\n");
      out.write("    border: 1px solid #9ba0a8;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    background: #a4a9b0;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    line-height: 16px;\r\n");
      out.write("    padding: 11px 0;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close{\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 32px;\r\n");
      out.write("    font-size:15px;\r\n");
      out.write("    background: #f8f9fa;\r\n");
      out.write("    border-top: 1px solid #ececec;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("    color : #1e2732;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close a{\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding-right: 14px;\r\n");
      out.write("    margin: 8px 16px 0 0;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    line-height: 16px;\r\n");
      out.write("    color: #757c8a;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close a:hover {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>멍멍이의 하루 - ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님의 쪽지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div style=\"margin-left: 10px; color: black;\">\r\n");
      out.write("  \t<div class=\"title\"><span style=\"color: #2e8de5\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>님의 쪽지</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th>제목</th>\r\n");
      out.write("\t<td style=\"font-weight: bold\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.titleLetter }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th>날짜</th>\r\n");
      out.write("\t<td>");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t<th>내용</th>\r\n");
      out.write("\t<td style=\"width: 528px; height: 400px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.contentLetter }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div style=\"text-align: center; margin-top: 20px;\">\r\n");
      out.write("   \t<button id =\"insert\" style=\"margin-right: 10px; margin-bottom: 10px;\" onclick=\"window.close();\">확인</button><button value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.numLetter }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"deleteletter\">삭제</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"close\" style=\"text-align: right;\"><a onclick=\"window.close();\">닫기X</a></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(document).on('click', '.deleteletter', function(){\r\n");
      out.write("    var num = $(this).val();\r\n");
      out.write("    console.log(\"num : \" + num);\r\n");
      out.write("    var numletter = num;\r\n");
      out.write("    console.log(\"numletter : \"+numletter);\r\n");
      out.write("    \r\n");
      out.write("    $.ajax({\r\n");
      out.write("      type : 'delete',\r\n");
      out.write("      url : '/hotel/letter/delete/'+numletter,\r\n");
      out.write("      headers : {\r\n");
      out.write("        'Content-Type' : 'application/json',\r\n");
      out.write("        'X-HTTP-Method-Override' : 'DELETE'\r\n");
      out.write("      },\r\n");
      out.write("    data : JSON.stringify({\r\n");
      out.write("        'numletter' : numletter\r\n");
      out.write("      }),\r\n");
      out.write("    success : function(result){\r\n");
      out.write("        if(result == 'success') {\r\n");
      out.write("        opener.parent.location='/hotel/letter/list';\r\n");
      out.write("        window.close();\r\n");
      out.write("        alert(\"쪽지 삭제 완료\")\r\n");
      out.write("        }\r\n");
      out.write("      } // end success  \r\n");
      out.write("    }); // end ajax                  \r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/letter/detail.jsp(157,5) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.dataLetter}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/letter/detail.jsp(157,5) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd HH시 mm분");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
